### PR TITLE
Add Q First & Last Occurrence of an element

### PR DESCRIPTION
**Pull request by Imbiber**
Using binary search , for a given array, we are finding the first and last occurrence of a given element .

### CODE REVIEW

**Comment by VGandhi27** [comment]
okay

**Comment by Imbiber** [comment]
Just checked , They have excluded this repo. Can you confirm from your side.

**Comment by VGandhi27** [comment]
It will take 7 days time

**Comment by VGandhi27** [comment]
This repository is the part of Hacktoberfest 2023

**Comment by VGandhi27** [comment]
> It will take 7 days time

from hactoberfest for checking your contribution

**Comment by Imbiber** [comment]
image

Earlier it was showing it will take them 7 days but now its saying its excluded.

**Comment by VGandhi27** [comment]
Sorry for the inconvenience cause, thank you for letting me know ,I will archive this repository

**Pull request merged**
